# Specify the base image
FROM python:3.11.0-slim-buster

# Set the working directory
WORKDIR /LUCRA_AI

# Copy the application files to the container
COPY . .

# Install dependencies (if any)

RUN ./init_setup.sh

# Expose the necessary ports
EXPOSE 3000

# Define the command to run the application
CMD python3 app.py

