"""empty message

Revision ID: 435ebcf6e9fc
Revises: 3c9b78409e81
Create Date: 2024-04-03 04:25:59.195234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435ebcf6e9fc'
down_revision = '3c9b78409e81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('named_entity', schema=None) as batch_op:
        batch_op.alter_column('entity_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)
        batch_op.alter_column('text_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    with op.batch_alter_table('text_data', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('text_data', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('named_entity', schema=None) as batch_op:
        batch_op.alter_column('text_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('entity_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
