"""empty message

Revision ID: 4b04ff43f67a
Revises: 8e925c1b8ea4
Create Date: 2024-04-03 03:02:45.686824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b04ff43f67a'
down_revision = '8e925c1b8ea4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('text_data',
    sa.Column('text_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('text_content', sa.Text(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default='CURRENT_db.TIMESTAMP', nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('text_id'),
    sa.UniqueConstraint('text_id')
    )
    op.create_table('named_entity',
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('text_id', sa.Integer(), nullable=True),
    sa.Column('entity_type', sa.Text(), nullable=False),
    sa.Column('entity_value', sa.String(length=255), nullable=False),
    sa.Column('entity_end', sa.Integer(), nullable=False),
    sa.Column('entity_start', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['text_id'], ['text_data.text_id'], ),
    sa.PrimaryKeyConstraint('entity_id'),
    sa.UniqueConstraint('entity_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('named_entity')
    op.drop_table('text_data')
    # ### end Alembic commands ###
